### ISSUE TITLE
Findings of CLI not displayed because filtered out by contentRoots

### ISSUE THREAD

**Issue by Circuitous** [nhat-phan/shit-cleaner#3]
The display of results seems to be broken in 19.3. The plugin showed 0 issues, although the CLI listed over 20. I also got a PluginException, but I do not know whether it is related.
`
com.intellij.diagnostic.PluginException: net.ntworld.intellijCodeCleaner.AnalyzeMenuAction (net.ntworld.intellijCodeCleaner.AnalyzeMenuAction): group with id "AnalyzeMenu" isn't registered; action will be added to the "Other" group [Plugin: com.github.nhat-phan.codecleaner]
`

**Comment by stefan-camilleri** [comment]
+1 same issue here (IntelliJ IDEA 2019.3 + Ubuntu 19.10)

**Comment by nhat-phan** [comment]
I found the root cause, unlike Kotlin/java on Intellij IDEA on other IDEs/languages there is no contentRoot at all, so result is filtered out. I'm going to release a new version (2019.2.1) which fix this issue, will be approved and available on the Intellij Plugin Repository within 2 days

FYI: contentRoots is a folder with small blue dot, it contains actual source code, I used it to filter out some result which may not relevant to the project
<img width="326" alt="Screen Shot 2019-12-15 at 21 01 26" src="https://user-images.githubusercontent.com/34987391/70868190-545ddf80-1f7e-11ea-900e-322aad3df9af.png">

**Comment by nhat-phan** [comment]
@Circuitous @Stefan-Z-Camilleri The new version is available now, could you guys please give it another try? thank you!

**Comment by stefan-camilleri** [comment]
@nhat-phan thank you, tested it, seems to work fine now.

**Comment by Circuitous** [comment]
@nhat-phan Working very well now, thanks alot.
